services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      ML_URL: "http://ml:8000"
      NODE_ENV: "production"
    depends_on:
      - ml
  ml:
    build: ./ml_service
    ports:
      - "8000:8000"
